# 配置tomcat

server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

# 配置源信息

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# mybatis配置项
mybatis:
  type-aliases-package: com.imooc.pojo  # 所有pojo类的所在路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件

# mybatis mapper 配置
# 通用Mapper 配置
mapper:
  mappers: com.immoc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL